// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function isLoading(param) {
  if (typeof param === "number") {
    return param !== 0;
  } else {
    return false;
  }
}

function isDone(param) {
  if (typeof param === "number") {
    return false;
  } else {
    return true;
  }
}

function flatMap(x, f) {
  if (typeof x === "number") {
    if (x !== 0) {
      return /* Loading */1;
    } else {
      return /* NotAsked */0;
    }
  } else {
    return Curry._1(f, x._0);
  }
}

function map(x, f) {
  if (typeof x === "number") {
    if (x !== 0) {
      return /* Loading */1;
    } else {
      return /* NotAsked */0;
    }
  } else {
    return {
            _0: Curry._1(f, x._0),
            [Symbol.for("name")]: "Done"
          };
  }
}

function getWithDefault(x, v) {
  if (typeof x === "number") {
    return v;
  } else {
    return x._0;
  }
}

exports.isLoading = isLoading;
exports.isDone = isDone;
exports.flatMap = flatMap;
exports.map = map;
exports.getWithDefault = getWithDefault;
/* No side effect */
